In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [15]:
data={
    "python":[ "yes","yes","no","yes","no","yes","no","no","yes","yes","yes","no","yes","no","no","yes","yes","no","no","yes" ],
    "machine learning":[ "yes","yes","no","yes","no","no","no","no","yes","yes","yes","no","yes","no","no","yes","yes","no","no","yes" ],
    "experince":[2,1,0,3,2, 0,4,1,2,3, 0,5,2,1,4, 3,2,0,5,1],
    "projects":[3,2,1,4,5, 0,4,1,2,5, 0,5,3,1,4, 3,2,0,5,1],
    "shortlisted":[ "yes","yes","no","yes","no","yes","no","no","yes","yes","yes","no","yes","no","no","yes","yes","no","no","yes" ] }

In [16]:
df=pd.DataFrame(data)
df

   python machine learning  experince  projects shortlisted
0     yes              yes          2         3         yes
1     yes              yes          1         2         yes
2      no               no          0         1          no
3     yes              yes          3         4         yes
4      no               no          2         5          no
5     yes               no          0         0         yes
6      no               no          4         4          no
7      no               no          1         1          no
8     yes              yes          2         2         yes
9     yes              yes          3         5         yes
10    yes              yes          0         0         yes
11     no               no          5         5          no
12    yes              yes          2         3         yes
13     no               no          1         1          no
14     no               no          4         4          no
15    yes              yes          3         3         yes
16    yes              yes          2         2         yes
17     no               no          0         0          no
18     no               no          5         5          no
19    yes              yes          1         1         yes

appling encoders on data

In [17]:
encode=LabelEncoder()
df["python"]=encode.fit_transform(df["python"])
df["machine learning"]=encode.fit_transform(df["machine learning"])
df["shortlisted"]=encode.fit_transform(df["shortlisted"])
df

    python  machine learning  experince  projects  shortlisted
0        1                 1          2         3            1
1        1                 1          1         2            1
2        0                 0          0         1            0
3        1                 1          3         4            1
4        0                 0          2         5            0
5        1                 0          0         0            1
6        0                 0          4         4            0
7        0                 0          1         1            0
8        1                 1          2         2            1
9        1                 1          3         5            1
10       1                 1          0         0            1
11       0                 0          5         5            0
12       1                 1          2         3            1
13       0                 0          1         1            0
14       0                 0          4         4            0
15       1                 1          3         3            1
16       1                 1          2         2            1
17       0                 0          0         0            0
18       0                 0          5         5            0
19       1                 1          1         1            1

In [18]:
X=df.drop("shortlisted",axis=1)
y=df["shortlisted"]

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=9)

In [20]:
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [21]:
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print(f"Name of Model: Gaussian NB and the Accuracy score: {accuracy_score(y_test, predictions)}")
print()
print(classification_report(y_test, predictions))
train = model.score(X_train, y_train)
test = model.score(X_test, y_test)
print(f"Train Score: {train} and Test Score: {test}")

Name of Model: Gaussian NB and the Accuracy score: 0.8

              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       1.00      0.67      0.80         3

    accuracy                           0.80         5
   macro avg       0.83      0.83      0.80         5
weighted avg       0.87      0.80      0.80         5

Train Score: 1.0 and Test Score: 0.8

In [22]:
def mymodel():
  name = input("Enter your name: ")
  # Changed inputs to expect 'yes'/'no' strings for categorical features
  python_val = input("Enter your value for python (yes/no): ")
  machine_learning_val = input("Enter your value for machine learning (yes/no): ")
  experince = int(input("Enter your value for experience: "))
  projects = int(input("Enter your value for projects: "))

  # Create a DataFrame from the new observation
  new_data = {
      "python": [python_val],
      "machine learning": [machine_learning_val],
      "experince": [experince],
      "projects": [projects]
  }
  df1 = pd.DataFrame(new_data)

  # Apply LabelEncoder to the categorical columns of the new DataFrame
  # It's important to use the same encoding logic as the training data.
  # Since LabelEncoder sorts categories, 'no' will be 0 and 'yes' will be 1.
  # We create a temporary encoder for this, assuming 'no' and 'yes' are the only categories.
  temp_encoder = LabelEncoder()
  # Fit to the possible categories ['no', 'yes'] to ensure consistent mapping
  temp_encoder.fit(['no', 'yes'])
  df1["python"] = temp_encoder.transform(df1["python"])
  df1["machine learning"] = temp_encoder.transform(df1["machine learning"])

  # Predict using the processed DataFrame df1
  predictions = model.predict(df1)

  if predictions[0] == 1:
    print(f"Hello {name}")
    print("You are shortlisted!")
  else:
    print(f"Hello {name}")
    print("You are not shortlisted.")

In [23]:
def mynewmodel():
  candidate_name=input("enter your name")
  pyhton=int(input("enter your values"))
  machinelearning=int(input("enter your values"))
  experince=int(input("enter your values"))
  projects=int(input("enter your values"))
  newobs=np.array([[pyhton,machinelearning,experince,projects]])
  newobs=[[pyhton,machinelearning,experince,projects]]
  prediction=model.predict(newobs)
  if prediction[0]==1:
    print("shortlisted")
  else:
      print("not shortlisted")

In [24]:
mymodel()

Enter your name: krit
Enter your value for python (yes/no): yes
Enter your value for machine learning (yes/no): yes
Enter your value for experience: 9
Enter your value for projects: 0
Hello krit
You are shortlisted!

In [25]:
mynewmodel()

enter your namekrit
enter your values78
enter your values89
enter your values60
enter your values0
shortlisted